name: start_get

on:
  # cron-job.org からの通知を受け取る設定
  repository_dispatch:
    types: [trigger-from-cronjob]
  
  # GitHub画面から手動で実行したい時用
  workflow_dispatch:
  
  # mainブランチにコードをプッシュした時用
  push:
    branches:
      - main

jobs:
  set-status:
    runs-on: ubuntu-latest
    steps:
      - name: ステータス変更（投稿待ち）
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"status":"投稿待ち"}' \
          https://number-board.onrender.com/setStatus